# function fish_greeting
# 	echo (set_color normal)
# 	echo (set_color purple) "                                                               ░░▒▒▓▓███▓▓▒▒░░                                                     █████████▓▓▒▒░░"
# 	echo (set_color purple) "                                                              ░░▒▒▓▓███▓▓▒▒░░                                                     █████████▓▓▒▒░░"
# 	echo (set_color purple) "                                                             ░░▒▒▓▓███▓▓▒▒░░"
# 	echo (set_color purple) "                          ░░▒▒▓▓██████████████████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓██████████████████████▓▓▒▒░░                   █████████▓▓▒▒░░░░▒▒▓▓████████████████████████▓▓▒▒░░"
# 	echo (set_color purple) "                         ░░▒▒▓▓█████████    █████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓█████████    █████████▓▓▒▒░░                   █████████▓▓▒▒░░░░▒▒▓▓███████████    █████████▓▓▒▒░░"
# 	echo (set_color purple) "                                           █████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓█████████    █████████▓▓▒▒░░                   █████████▓▓▒▒░░░░▒▒▓▓███████████    █████████▓▓▒▒░░"
# 	echo (set_color purple) "                       ░░▒▒▓▓██████████████████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓██████████████████████▓▓▒▒░░                   █████████▓▓▒▒░░░░▒▒▓▓███████████    █████████▓▓▒▒░░"
# 	echo (set_color purple) "                      ░░▒▒▓▓█████████    █████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓█████████                   ░░▒▒▓▓█████████    █████████▓▓▒▒░░░░▒▒▓▓███████████    █████████▓▓▒▒░░"
# 	echo (set_color purple) "                     ░░▒▒▓▓█████████    █████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓█████████    █████████▓▓▒▒░░░░▒▒▓▓█████████    █████████▓▓▒▒░░░░▒▒▓▓███████████    █████████▓▓▒▒░░"
# 	echo (set_color purple) "                    ░░▒▒▓▓██████████████████████▓▓▒▒░░░░▒▒▓▓███▓▓▒▒░░░░▒▒▓▓██████████████████████▓▓▒▒░░░░▒▒▓▓██████████████████████▓▓▒▒░░░░▒▒▓▓████████████████████████▓▓▒▒░░"
# end


#echo (set_color cyan)  "            ▓▒▒▒▒▒▒▒▒▒   ▒▒▒▒▒    ▒▒▒▒▒    ▒▒▒▒▒ ▒▒▒▒    ▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒   ▒▒▒▒▒▒   ▒▒▒▒          " 
#echo (set_color cyan)  "          ▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒   ▒▒▒▒▒   ▒▒▒▒▒▒ ▒▒▒▒    ▒▒▒▒ ▒▒▒▒   ▒▒▒▒▒  ▒▒▒▒▒▒   ▒▒▒▒          " 
#echo (set_color cyan)  "          ▒▒▒▒          ▒▒▒▒▒▒▒   ▒▒▒▒▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒    ▒▒▒▒ ▒▒▒▒   ▒▒▒▒▒ ▓▒▒▒▒▒▒▒  ▒▒▒▒          " 
#echo (set_color cyan)  "          ▒▒▒▒▒▒▒▒▒▒   ▒▒▒▒ ▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒    ▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒  ▒▒▒▒          " 
#echo (set_color cyan)  "           ▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒ ▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒    ▒▒▒▒ ▒▒▒▒▒▒▒      ▒▒▒▒ ▒▒▒▒  ▒▒▒▒         " 
#echo (set_color cyan)  "            ▒▒▒▒▒▒▒▒▒▒▓▒▒▒   ▒▒▒▒ ▒▒▒▒▒      ▓▒▒ ▒▒▒▒    ▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒   ▒▒▒▒  ▒▒▒▓ ▒▒▒▒         " 
#echo (set_color cyan)  "                   ▓▒▒▒▒▒▒▒   ▒▒▒ ▒▒▒▒  ▒▒▒ ▒▒▒▒ ▒▒▒▒▒▓ ▒▒▒▒▒ ▒▒▒▒▓ ▒▒▒▒▓ ▒▒▒▒   ▒▒▒▒ ▒▒▒▒         " 
#echo (set_color cyan)  "                    ▓▓▓▓▓▓    ▓▓▓▓▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓   ▓▓▓   ▓▓▓▓ ▓▓▓▓    ▓▓▓ ▓▓▓▓         " 
#echo "" 
#echo (set_color red)   "                                                            ▓                                       " 
#echo (set_color red)   "                                                         ▓▓▓               ▓                        " 
#echo (set_color red)   "                                                      ▓▓▓▓         ▓      ▓▓                        " 
#echo (set_color red)   "                                                     ▓▓▓▓          ▓     ▓▓                         " 
#echo (set_color red)   "                                                     ▓▓▓          ▓▓     ▓                          " 
#echo (set_color red)   "                          ▓            ▓ ▓          ▓▓▓▓▓ ▓      ▓▓                                 " 
#echo (set_color red)   "                          ▓            ▓ ▓     ▓    ▓▓▓▓▓▓▓   ▓                                     " 
#echo (set_color red)   "                          ▓           ▓▓        ▓   ▓▓▓▓▓▓▓▓▓▓▓       ▓                             " 
#echo (set_color red)   "                          ▓▓           ▓▓       ▓▓▓▓▓▓▓▓▓▓▓▓ ▓    ▓  ▓                              " 
#echo (set_color red)   "                                        ▓▓   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓      ▓▓     ▓    ▓                      " 
#echo (set_color red)   "                                  ▓▓    ▓▓   ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓    ▓▓▓▓   ▓▓    ▓                      " 
#echo (set_color red)   "                               ▓       ▓ ▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓    ▓▓                     " 
#echo (set_color red)   "                        ▓        ▓▓       ▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓   ▓  ▓    ▓                     " 
#echo (set_color red)   "                       ▓▓  ▓     ▓▓ ▓  ▓ ▓▓▓▓▓▓▓▓▓▓▓▓ ▓  ▓▓▓▓▓▓ ▓▓▓▓ ▓   ▓    ▓                     " 
#echo (set_color red)   "                        ▓▓ ▓▓▓▓▓ ▓▓  ▓ ▓▓ ▓▓▓▓▓▓▓▓▓ ▓  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓ ▓ ▓▓                         " 
#echo (set_color red)   "                            ▓▓▓▓▓ ▓▓  ▓▓▓▓▓▓▓  ▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓                         " 
#echo -n (set_color red)"                            ▓▓   "
#echo -n (set_color cyan)                                "▒▓▒▒"
#echo (set_color red)                                        " ▓▓▓▓▓▓▓  ▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓ ▓▓                          " 
#echo -n (set_color red)"                      ▓        "
#echo -n (set_color cyan)                              "▒▒▒▒▒▒▒"
#echo (set_color red)                                         "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓▓   ▓ ▓▓▓                           " 
#echo -n (set_color red)"                           ▓  "
#echo -n (set_color cyan)                             "▒      ▒"
#echo (set_color red)                                         "  ▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      ▓▓▓▓▓▓                         " 
#echo -n (set_color red)"                           ▓▓   "
#echo -n (set_color cyan)                               "▒▒ "
#echo -n (set_color red)                                   "▓"
#echo -n (set_color cyan)                                   " ▒▒   "
#echo (set_color red)                                             "▓▓▓▓▓▓▓ ▓ ▓▓▓▓▓▓▓▓▓       ▓▓▓▓▓▓                         " 
#echo -n (set_color red)"                         ▓▓▓▓▓  "
#echo -n (set_color cyan)                               "▒▒"
#echo -n (set_color cyan)                                 "    ▓ "
#echo (set_color red)                                           "    ▓ ▓▓ ▓ ▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓                         " 
#echo -n (set_color red)"                         ▓▓▓▓▓▓    "
#echo -n (set_color cyan)                                  "▒▒▒▒ ▒ ▒   "
#echo (set_color red)                                                 " ▓▓▓▓▓▓▓         ▓      ▓▓▓▓▓▓                          " 
#echo -n (set_color red)"                          ▓▓▓▓  "
#echo -n (set_color cyan)                               "▒ ▓ "
#echo -n (set_color cyan)                                   "▒ ▒▒"
#echo (set_color red)                                           "      ▓▓▓▓▓▓▓▓▓          ▓▓ ▓▓▓▓                           " 
#echo -n (set_color red)"                           ▓▓▓"
#echo -n (set_color cyan)                             " ▒▓ ▒▒▒▒▒▒▒▒▒▒▒ ▒ "
#echo -n (set_color red)                                               "▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓"
#echo (set_color cyan)                                                                         "▒▒                          " 
#echo -n (set_color red)"                          ▓▓  ▓ "
#echo -n (set_color cyan)                               "▒▒  ▒▒▒▒    ▒▒   "
#echo -n (set_color red)                                                 "▓▓▓▓▓ ▓▓  ▓▓▓▓▓▓  ▓▓ "
#echo (set_color cyan)                                                                        "▒▒ ▒▒                        " 
#echo -n (set_color red)"                                ▓          "
#echo -n (set_color cyan)                                          "▒▒ ▒▒  "
#echo -n (set_color red)                                                  "▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ "
#echo (set_color cyan)                                                                     "▒▒▒▒ ▒▒ ▒                       " 
#echo -n (set_color red)"                              ▓        "
#echo -n (set_color cyan)                                      "▒▒▒▒▒▒▒▒▒"
#echo -n (set_color red)                                                " ▓▓▓▓▓▓▓▓  ▓▓▓▓▓"
#echo (set_color cyan)                                                                  " ▒▒▒ ▒▒▒▒  ▒▒                      " 
#echo -n (set_color red)"                                     ▓"
#echo -n (set_color cyan)                                     "▒▒▒▒▒ ▒▒▒▒ "
#echo -n (set_color red)                                                 "▓▓▓▓  ▓▓ ▓▓▓ ▓▓ "
#echo -n (set_color cyan)                                                                "▒▒▒▒▒  ▒▒▒"
#echo (set_color red)                                                                              "▓                       " 
#echo -n (set_color cyan)"                                       ▒▒▒   ▒▒▒▒       "
#echo -n (set_color red)                                                         "▓▓"
#echo -n (set_color cyan)                                                          "▒▒▒"
#echo -n (set_color red)                                                              "▓▓▓   ▓"
#echo (set_color cyan)                                                                       "▒▒▒▒▒▒▒                        " 
#echo -n (set_color cyan)"                                      ▒▒▒▒▒▒▒ ▒▒▒▒ "
#echo -n (set_color red)                                                    "▓▓▓▓▓ "
#echo -n (set_color cyan)                                                          "▒▒▒▒▒"
#echo (set_color red)                                                                  "▓▓                                   " 
#echo -n (set_color cyan)"                                   ▒▒▒▒▒▒▒               "
#echo -n (set_color red)"▓"
#echo (set_color cyan)"▒▒▒▒▒▒                                   " 
#echo (set_color cyan)"                                ▒▒▒▒▒▒▒▒  ▒             ▒  ▒▒▒▒▒▒▒▒▒                               " 
#echo -n (set_color red)"                                      ▓   "
#echo -n (set_color cyan)"▒▒▒ ▒      ▒ ▒▒       "
#echo -n (set_color red)"▓"
#echo -n (set_color cyan)"▒▒▒"
#echo (set_color red)"▓                              " 
#echo -n (set_color red)"                                     ▓▓▓     ▓▓▓▓▓▓▓▓▓ "
#echo -n (set_color cyan)"▒"
#echo (set_color red)"   ▓▓▓                                     " 
#echo (set_color red)"                                       ▓▓▓▓▓▓▓ ▓▓▓▓  ▓▓▓▓▓▓▓                                       " 
#echo (set_color red)"                                          ▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓                                          " 
#echo (set_color red)"                                             ▓▓▓▓▓▓▓▓▓                                             " 
#echo (set_color red)"                                              ▓▓▓▓▓▓                                               " 

function fish_greeting

echo (set_color blue)"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣤⣤⣤⣄⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⣷⣶⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⣀⣤⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⣠⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀"
echo "⠘⠛⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠉⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀"
echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣤⣤⣤⣤⣀⡀"
echo -n "⠀⠀⠀⠀⠀⠀⠀⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀"
echo -n (set_color reset)"⢀⡀⠀"
echo (set_color blue)"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁"
echo -n "⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀"
echo -n (set_color reset)"⢀⣾⣿⠃⠀"
echo (set_color blue)"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀"
echo -n "⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧"
echo -n (set_color reset)"⣠⣿⡿⠃⠀⠀"
echo (set_color blue)"⢸⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⠋⠀⠀⠀⠀"
echo -n "⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
echo -n (set_color yellow)"⣿⣿⣿"
echo -n (set_color reset)"⣿⣿⣿"
echo -n (set_color yellow)"⣿⣿⣅⠀⠀⠀⠀"
echo (set_color blue)"⠘⣿⣿⣿⣿⣿⠛⢡⣾⠟⠁⠀⠀⠀⠀⠀"
echo -n "⠀⠀⠀⢰⣿⣿⣿⣿⣿⠿⠟⠛⠋⠉⠉⠉⠉"
echo -n (set_color yellow)"⠉⠉⠙⢿"
echo -n (set_color reset)"⣿⣿⣿"
echo -n (set_color yellow)"⣿⣿⣶⣶⣤⣤"
echo (set_color blue)"⣝⣻⣿⡿⢃⠴⠋⠀⠀⠀⠀⠀⠀⠀⠀"
echo -n "⠀⠀⠀⣿⡿⠟⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo -n (set_color yellow)"⠈⠛⠿"
echo -n (set_color reset)"⣿⣿"
echo -n (set_color yellow)"⣿⣿⣿⣿⣿⣿⣥⣒"
echo (set_color blue)"⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo -n "⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo -n (set_color yellow)"⠉⠙⠛⠛⠛⠋"
echo (set_color black)"⠙⠻⠿⠿⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀"
echo (set_color reset)""

set WEATHER (curl -s 'wttr.in/Paris?format=2')

echo (set_color reset) ""
echo "Hey choom, take care !"
echo "NC's weather: $WEATHER"



end

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# <<< conda initialize <<<
set -gx PATH /home/apetitco/.local/funcheck/host $PATH

# Created by `pipx` on 2024-12-11 09:53:41
set PATH $PATH /home/apetitco/.local/bin
